import Link from "next/link";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
// TODO REMOVE LINKS FROM PAGES
export default function RootLayout({ children, }: { children: React.ReactNode}) {
  return (
    <html lang="en">
      <body>
	<nav>
		<Link href="/ssr">Go to SSR</Link>
		<br/>
		<Link href="/csr">Go to CSR</Link>
		<br/>
		<Link href="/">Go to Static</Link>
	</nav>
	
	{children}

	</body>
    </html>
  )
}
